version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: bash -c "cd alembic && alembic revision --autogenerate -m 'init' && python -m alembic upgrade head"
    ports:
      - 8000:8000
    networks:
    - my-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
    - my-network